version: '3.8'

services:
  weixin-search:
    build: .
    container_name: weixin-search-mcp
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PLAYWRIGHT_BROWSERS_PATH=/app/.playwright
    volumes:
      - playwright_cache:/app/.playwright
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'

volumes:
  playwright_cache:
    driver: local